### ISSUE TITLE
OutputCache does not reset request stream after being copied resulting in failed modelbinding

### ISSUE THREAD

**Issue by koenvanderlinden** [aspnet/AspNetOutputCache#8]
Because of this line:
https://github.com/aspnet/AspNetOutputCache/blob/d086284a13f34cf35090495ea8aa994bd2be5c48/src/OutputCacheModuleAsync/OutputCacheHelper.cs#L946

the request inputstream position is not pointing to 0 after it's being copied. The result is that the request pipeline cannot read the contents of the stream. In our project the binding of the request to the controller method viewmodel failed. The viewmodel was always empty.
When setting the request.stream position to 0, fixed the problem.

**Comment by StephenMolloy** [comment]
Fixed in #12.
Our package verification team is OOF for a bit. But a nuget update should pop up within the month.
